steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.8'
  inputs:
    versionSpec: '3.8'

- task: AzureCLI@2
  displayName: Install Job Requirements
  inputs:
    azureSubscription: $(AZURE_RM_SVC_CONNECTION)
    scriptType: bash
    scriptLocation: inlineScript
    workingDirectory: $(System.DefaultWorkingDirectory)
    inlineScript: |
      set -e # fail on error
      python -m pip install --upgrade pip
      pip install -r devops/pipeline/requirements/execute_job_requirements.txt
      az version


