
steps:
  - task: AzureCLI@2
    displayName: Register Azure ML environment (conda)
    continueOnError: false
    inputs: 
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      scriptType: bash
      workingDirectory: $(System.DefaultWorkingDirectory)
      scriptLocation: inlineScript
      inlineScript: |
         python mlops/nyc-taxi/src/prep_environment.py \
          --subscription_id $(SUBSCRIPTION_ID) \
          --resource_group_name $(RESOURCE_GROUP_NAME) \
          --workspace_name $(WORKSPACE_NAME) \
          --env_base_image_name $(ENV_BASE_IMAGE_NAME) \
          --conda_path $(CONDA_PATH) \
          --environment_name $(ENVIRONMENT_NAME) \
          --version_number $(BUILD.BUILDID)

