
steps:
  - task: AzureCLI@2
    displayName: Execute Azure ML pipeline job
    continueOnError: false
    inputs: 
      azureSubscription: $(AZURE_RM_SVC_CONNECTION)
      scriptType: bash
      workingDirectory: $(System.DefaultWorkingDirectory)
      scriptLocation: inlineScript
      inlineScript: ${{parameters.exec_environment}}
