variables:
- name: EXPERIMENT_NAME
  value: $(EXPERIMENT_BASE_NAME)_${{parameters.exec_environment}}_$(Build.BuildID)
- name: DISPLAY_NAME
  value: $(DISPLAY_BASE_NAME)_${{parameters.exec_environment}}_$(Build.BuildID)
- name: MODEL_NAME
  value: $(MODEL_BASE_NAME)_${{parameters.exec_environment}}_$(Build.BuildID)
- name: PIPELINE_NAME
  value: $(pipeline_base_name)_${{parameters.exec_environment}}_$(Build.BuildID)