# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Workflow that deploys the infrastructure and sets up compute & data in the AML workspace

on: workflow_dispatch

env: 
  azureMgrConnection: 'sdk2deploymenttest'
  environmentName: 'DEV'
  resourceGroup: 'rg-pvtws-mlops-sdkv2-bicep-test'
  location: 'west us 2'


####################
##  DEPLOY INFRA  ##
####################
jobs: 
  name: deployinfra_dev
  runs-on: ubuntu-latest
  steps:
    - name: 'Copy templates'
    - uses: actions/checkout@v2

    - name: 'Deploy azure machine learning workspace'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az --version
          az deployment group create --resource-group 'rg-pvtws-mlops-sdkv2-bicep-test' \
          --template-file main.bicep \
          --parameters \
            location='canadacentral' \
            storageAccount='samlopsdevtmpl' \
            keyVaultName='kvmlopsdevtmpl' \ 
            appInsightsName='aimlopsdevtmpl' \
            containerRegistryName='crmlopsdevtmpl' \
            amlWorkspaceName='mlopsdevtmpl'
