pr: none
trigger:
  branches:
   include:
     - main
  paths:
    include:
      - devops/*
      - mlops/common/*
      - src/nyc_taxi/*
      - mlops/nyc-taxi/*
      - src/shared/*

pool:
  vmImage: ubuntu-latest

parameters:
 - name: exec_environment
   displayName: "Execution Environment"
   default: "dev"

variables:
- group: MLOps-${{parameters.exec_environment}}-VG

stages:
    - stage: execute
      displayName: execute_job
      variables:
      - template: templates/experiment_variables.yml
        parameters:
          exec_environment: ${{parameters.exec_environment}}
      jobs:
      - job: Execute_Job_Pipeline
        steps:
        - template: templates/get_connection_details.yml
        - template: templates/configure_azureml_agent.yml
        - template: templates/create_compute.yml
        - template: templates/create_environment.yml
        - template: templates/execute_mlops_pipeline.yml
          parameters:
            pipeline_pat: $(PIPELINEPAT)
            exec_environment: ${{parameters.exec_environment}}

