name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - pandas
    - scikit-learn
    - mlflow
    - azureml-mlflow
    - mldesigner==0.1.0b4
    - azure-ai-ml==1.0.0
    - azure-identity==1.11.0
