parameters:
- name: environmentName
  type: string
- name: azureMgrConnection
  type: string
- name: resourceGroup
  type: string
- name: location
  type: string     
- name: variablesTemplateBase
  type: string
- name: storageAccount
  type: string
- name: keyVaultName
  type: string
- name: appInsightsName  
  type: string
- name: containerRegistryName  
  type: string
- name: amlWorkspaceName  
  type: string  
  
  bicep-deploy:
  name: 'Bicep Deploy'
  #TODO can we easily determine if there are any changes to deploy?
  if: github.ref == 'refs/heads/main' 
  runs-on: ubuntu-latest
  environment: production
  
  steps:
  # Checkout the repository to the GitHub Actions runner
  - name: Checkout
    uses: actions/checkout@v3

  # Authenticate to Az CLI using OIDC
  - name: 'Az CLI login'
    uses: azure/login@v1
    with:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
  # Deploy
  - name: "Bicep Deployment"
    uses: Azure/cli@v1
    with:
      inlineScript: |
      az deployment group create \
          --name deploy-${{ github.run_id }} \
          --resource-group '${{parameters.resourceGroup}}'          
          --template-file main.bicep \
          --parameters location='${{parameters.location}}' storageAccount='${{parameters.storageAccount}}' keyVaultName='${{parameters.keyVaultName}}' \
          appInsightsName='${{parameters.appInsightsName}}' containerRegistryName='${{parameters.containerRegistryName}}' amlWorkspaceName='${{parameters.amlWorkspaceName}}'