name: Build validation pipeline
on:
  workflow_call:

jobs:
  Build_Validation_Pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r devops/pipeline/requirements/build_validation_requirements.txt
      - name: Lint with flake8
        run: flake8 .
      - name: Run Unit Tests
        if: ${{ success() }}
        run: pytest  --ignore=sandbox/ --junitxml=junit/test-results.xml --cov=. --cov-report=xml
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: "**/test-*.xml"
      
      