name: My Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade   pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r -r devops/pipeline/requirements/build_validation_requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --ignore=sandbox/ --junitxml=junit/test-results.xml
    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path:  '**/test-*.xml'
    - name: Build
      run: |
        echo "test"
        echo "pipeline"
